### ISSUE TITLE
Milestone: Vac.dev public repositioning

### ISSUE THREAD

**Issue by oskarth** [vacp2p/vac.dev#84]
# Problem

As we are moving from just focusing on just Waku/secure messaging to that being one specific project, we want to update our public positioning. This was a topic during offsite, and this milestone is about making sure we capture all of this work.

## List

- [ ] https://github.com/vacp2p/research/issues/112
- [ ] https://github.com/vacp2p/vac.dev/issues/82
- [ ] https://github.com/vacp2p/vac.dev/issues/73

- [ ] Update Twitter
- [ ] Update Github profile

- Might be more?

**Comment by oskarth** [comment]
We also want a place to put papers.

- Publications -> Blog and papers
- Libraries? -> Repos

**Comment by fryorcraken** [comment]
Is there a decision on the tag line?

**Comment by oskarth** [comment]
@fryorcraken Under https://staging.vac.dev/ it is currently `Vac - Communication & Privacy` - did `Vac - Communication, Privacy, Etc` before but ended up with too many Etc so trying this out
